version: '2'

services:
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    restart: always
    container_name: kafka-server
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.199.121  # 宿主机ip
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.199.121:9092
    volumes:
    - ./kafka/logs:/kafka
    networks:
      - zk_network

  zookeeper:
    image: zookeeper:3.4.14
    restart: always
    container_name: zookeeper
    ports:
    - "2181:2181"
    volumes:
    - ./zookeeper/data:/data
    - ./zookeeper/datalog:/datalog
    networks:
      - zk_network

networks:
  zk_network:
    external: true