# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
  application:
    name:  spring-boot-mybatis-plus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    password: root
    username: root
logging:
  level:
    com.yunus.mapper: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      update-strategy: not_null
      table-underline: true