// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.yunus.protobuf;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yunus_protobuf_RPCDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yunus_protobuf_RPCDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yunus_protobuf_RPCDateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yunus_protobuf_RPCDateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\022com.yunus.protobuf\"\"" +
      "\n\016RPCDateRequest\022\020\n\010userName\030\001 \001(\t\"%\n\017RP" +
      "CDateResponse\022\022\n\nserverDate\030\001 \001(\t2f\n\016RPC" +
      "DateService\022T\n\007getDate\022\".com.yunus.proto" +
      "buf.RPCDateRequest\032#.com.yunus.protobuf." +
      "RPCDateResponse\"\000B)\n\022com.yunus.protobufB" +
      "\021RPCDateServiceApiP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_yunus_protobuf_RPCDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yunus_protobuf_RPCDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yunus_protobuf_RPCDateRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_com_yunus_protobuf_RPCDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yunus_protobuf_RPCDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yunus_protobuf_RPCDateResponse_descriptor,
        new java.lang.String[] { "ServerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
